Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -15,6 +15,10 @@ jobs:
         uses: actions/checkout@v3
       - name: Deploying to Development
         run: echo "Deploying to Development..."
+      - name: Run a script that throws an error
+        run: |
+          echo "Simulating a failure..."
+          exit 1
 
   deploy-to-prod:
     name: Deploy to Production
